services:
  # Common configuration for all of our core uservices
  oada-uservice:
    build:
      context: ./oada
    restart: unless-stopped
    networks:
      - startup_net
      - kafka_net
      - arango_net
    volumes:
      - ./oada/oada-srvc-docker-config.js:/oada-srvc-docker-config.js # for debug?
    environment:
      - NODE_ENV=${NODE_ENV-development}
      - DEBUG=${DEBUG-*}
      # Should just be an external script someone can run on their instance?
      - arangodb__ensureDefaults="true"
      - DOMAIN=${DOMAIN:-localhost}
      - NODE_TLS_REJECT_UNAUTHORIZED
      - PINO_TRANSPORT=${PINO_TRANSPORT-yarn g:pretty --colorize}
      # These should just be part of the release compose file
      #- NODE_ENV=${NODE_ENV-production}
      #- DEBUG=${DEBUG-*:error,*:warn,*:info}
