services:
  # Common configuration for all of our core uservices
  oada-uservice:
    build:
      context: ./oada
    restart: unless-stopped
    networks:
      - startup_net
      - kafka_net
      - arango_net
    volumes:
      - ./oada/oada-srvc-docker-config.js:/oada-srvc-docker-config.js # for debug?
    environment:
      # Default to loading packaged default config?
      - CONFIG=${OADA_CONFIG-/oada-srvc-docker-config.js}
      - NODE_ENV=${NODE_ENV-development}
      - DEBUG=${DEBUG-*}
      - PINO_LEVEL
      - DEBUG_HIDE_DATE
      - DEBUG_COLORS
      - DEBUG_DEPTH
      - DEBUG_SHOW_HIDDEN
      # Should just be an external script someone can run on their instance?
      - arangodb__ensureDefaults=true
      - DOMAIN=${DOMAIN:-localhost}
      - NODE_TLS_REJECT_UNAUTHORIZED
      - PINO_TRANSPORT=${PINO_TRANSPORT-yarn g:pretty -clti pid,hostname}
      # Allow changing arangodb URL (e.g., to use external arango)
      - ARANGODB_URL=${ARANGODB_URL-http://arangodb:8529}
      # Allow changing kafka brokers (e.g., to use external kafka)
      - KAFKA_BROKERS=${KAFKA_BROKERS-kafka:9092}
