version: '3'

services:
  # In development, put the dummy users/tokens into database
  startup:
    environment:
      - DEBUG=*
      - arangodb__ensureDefaults="true"

  arangodb:
    ports:
      - 8529:8529
