version: '3.7'

volumes:
  # Volume for code sync from host
  code:

# Common mutagen related configuration overrides for all of our core uservices
x-oada-uservice: &oada-uservice
  volumes:
    # Mount host code over images in development mode
    - code:/oada

services:
  # Service to intitialize node_modules in dev?
  yarn:
    image: oada/docker-base-node
    volumes:
      - code:/oada
    entrypoint: ['yarn', '--cwd', '/oada']
    command: install

  startup: *oada-uservice
  auth: *oada-uservice
  http-handler: *oada-uservice
  sync-handler: *oada-uservice
  write-handler: *oada-uservice
  users: *oada-uservice
  token-lookup: *oada-uservice
  rev-graph-update: *oada-uservice
  graph-lookup: *oada-uservice
  well-known: *oada-uservice
  admin: *oada-uservice
  webhooks: *oada-uservice
  permissions-handler: *oada-uservice
  shares: *oada-uservice

# Set up Mutagen synchronization
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: './'
      beta: 'volume://code'
      mode: 'one-way-replica'
      ignore:
        paths:
          # Don't map host/local node_modules into conainters
          - 'node_modules'
