{{- if not .Values.kafka.brokers }}
apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "oada.chart.labels" . | nindent 4 }}
spec:
  image: 'vectorized/redpanda'
  version: 'latest'
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  configuration:
    autoCreateTopics: true
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
    pandaproxyApi:
      - port: 8082
    adminApi:
      - port: 9644
    developerMode: {{ .Values.global.development }}
{{- end }}