---
apiVersion: v1
kind: Service
metadata:
  name: http-handler
  labels:
    app: http
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-handler
  labels:
    app: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - env:
            - name: CONFIG
              value: /oada.config.js
            - name: DEBUG
              value: '*:error,*:warn,*:info'
            - name: DOMAIN
              value: localhost
            - name: NODE_ENV
              value: production
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: PINO_TRANSPORT
              value: yarn g:pretty -clti pid,hostname
            - name: arangodb__ensureDefaults
              value: 'true'
          image: oada/http-handler:edge
          name: http-handler
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /oada/binary
              name: binary-data
      restartPolicy: Always
      volumes:
        - name: binary-data
