apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: write-handler
  name: write-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: write-handler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: write-handler
    spec:
      containers:
        - env:
            - name: CONFIG
              value: /oada.config.js
            - name: DEBUG
              value: '*:error,*:warn,*:info'
            - name: DOMAIN
              value: localhost
            - name: NODE_ENV
              value: production
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: PINO_TRANSPORT
              value: yarn g:pretty -clti pid,hostname
          image: oada/write-handler:edge
          name: write-handler
      restartPolicy: Always
