oada:
  # oada.domain is the domain for this OADA instance
  domain: localhost
  # oada.ingress is whether to create ingresses into the OADA API
  ingress: true
  # oada.tag is the Docker tag for the OADA images
  tag: edge
  # oada.services is the list of oada services to deploy
  services:
    http-handler:
      http: true
    auth:
      http: true
    shares: {}
    rev-graph-update: {}
    sync-handler: {}
    users: {}
    webhooks: {}
    well-known: {}
    write-handler: {}
  # oada.users is a list of users to be created
  users:
    - name: admin
      admin: true
      scope: all:all
  resources: {}

global:
  # global.development is whether to enable development/debug features not meant for production use
  development: false
