packageExtensions:
  mocha@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true
  fastify-sensible@*:
    peerDependencies:
      fastify: "*"
  fastify-cors@*:
    peerDependencies:
      fastify: "*"
  fastify-helmet@*:
    peerDependencies:
      fastify: "*"
  fastify-bearer-auth@*:
    peerDependencies:
      fastify: "*"
  fastify-websocket@*:
    peerDependencies:
      fastify: "*"
      "@types/ws": "*"
  middie@*:
    peerDependencies:
      fastify: "*"
  express@*:
    peerDependencies:
      ejs: "*"
    peerDependenciesMeta:
      ejs:
        optional: true
  oauth2orize-openid@*:
    dependencies:
      oauth2orize: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
