# TODO: Don't push images if we find vulnerabilities?
name: Check OADA Dockerfiles with Snyk

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '25 20 * * 4'

jobs:
  dockers:
    runs-on: ubuntu-latest

    outputs:
      contexts: ${{ steps.contexts.outputs.list }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Find Docker Contexts
        id: contexts
        run: |
          SERVICES=$(find -name Dockerfile | sed s/\\/Dockerfile$// | sed s/^\.\\/// | tr '\n' ',' | sed 's/,/","/g' | sed 's/^/["/' | sed 's/,"$/]/')
          echo ::set-output name=list::${SERVICES}

  build-dockers:
    needs: dockers

    strategy:
      matrix:
        context: ${{ fromJson(needs.dockers.outputs.contexts) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache docker layers
        if: ${{ !env.ACT }} # Awaiting ACT version after 0.2.17 for this feature
        uses: actions/cache@v2.1.5
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v2.4.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          platforms: linux/amd64
          load: true
          tags: dut:test
          build-args: |
            GIT_REF=${{ github.sha }}
          labels: |
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        # Don't break workflow on errros?
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: dut:test
          args: --org=oada --file=${{ matrix.context }}/Dockerfile

      # TODO: Is this making the duplicate alerts??
      #- name: Secure Code Warrior
      #  uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
      #  with:
      #    inputSarifFile: ./snyk.sarif
      #    outputSarifFile: ./securecodewarrior.sarif

      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          #sarif_file: ./securecodewarrior.sarif
          sarif_file: ./snyk.sarif
